-- liquibase formatted sql

-- changeset salikhdev:1770038409044-1
CREATE TABLE resource
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    original_name VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    size          BIGINT                                  NOT NULL,
    key           VARCHAR(255)                            NOT NULL,
    url           VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    extension     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_resource PRIMARY KEY (id)
);

