-- liquibase formatted sql

-- changeset salikhdev:1769176597528-1
CREATE TABLE _user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255),
    role       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    avatar_url VARCHAR(255),
    balance    DECIMAL                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

-- changeset salikhdev:1769176597528-2
ALTER TABLE _user
    ADD CONSTRAINT uc__user_email UNIQUE (email);

