-- liquibase formatted sql

-- changeset salikhdev:1769436853761-1
CREATE TABLE courses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    price      DECIMAL                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

-- changeset salikhdev:1769436853761-2
CREATE TABLE group_students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id   BIGINT                                  NOT NULL,
    student_id BIGINT                                  NOT NULL,
    joined_at  date                                    NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_students PRIMARY KEY (id)
);

-- changeset salikhdev:1769436853761-3
CREATE TABLE groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    number     BIGINT                                  NOT NULL,
    capacity   BIGINT                                  NOT NULL,
    mentor_id  BIGINT,
    course_id  BIGINT,
    start_time time WITHOUT TIME ZONE                  NOT NULL,
    end_time   time WITHOUT TIME ZONE                  NOT NULL,
    start_date date                                    NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

-- changeset salikhdev:1769436853761-4
ALTER TABLE _user
    ADD birth_date date;

-- changeset salikhdev:1769436853761-5
ALTER TABLE groups
    ADD CONSTRAINT uc_groups_number UNIQUE (number);

-- changeset salikhdev:1769436853761-6
ALTER TABLE groups
    ADD CONSTRAINT FK_GROUP_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

-- changeset salikhdev:1769436853761-7
ALTER TABLE groups
    ADD CONSTRAINT FK_GROUP_CREATED_BY FOREIGN KEY (created_by) REFERENCES _user (id);

-- changeset salikhdev:1769436853761-8
ALTER TABLE groups
    ADD CONSTRAINT FK_GROUP_MENTOR FOREIGN KEY (mentor_id) REFERENCES _user (id);

-- changeset salikhdev:1769436853761-9
ALTER TABLE group_students
    ADD CONSTRAINT FK_GROUP_STUDENTS_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

-- changeset salikhdev:1769436853761-10
ALTER TABLE group_students
    ADD CONSTRAINT FK_GROUP_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES _user (id);

-- changeset salikhdev:1769436853761-11
ALTER TABLE _user
    DROP COLUMN balance;

